### ISSUE TITLE
No package matching 'origin-docker-excluder-1.4.0*

### ISSUE THREAD

**Issue by moortimis** [openshift/origin-gce#30]
Hi there, came across the following issue on CentOS 7.3. I can see that 'origin-docker-excluder' exists, but not 'origin-docker-excluder-1.4.0*'

```
fatal: [ocp-ig-n-3d0g]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'origin-docker-excluder-1.4.0*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-1.4.0*' found available, installed or updated"]}
```

Be nice to support multi-os deployments.

**Comment by smarterclayton** [comment]
Should be fixed now, otherwise please open an issue on openshift-ansible.
